"""Persisted planner artifacts (R4) — day / week / month markdown output."""

from __future__ import annotations

import json
import logging
from datetime import datetime

from sqlalchemy import Column, DateTime, Integer, String, Text

from . import Base

logger = logging.getLogger(__name__)


class PlannerOutput(Base):
    """Structured planner content generated by proactive tasks."""

    __tablename__ = "planner_outputs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    scope = Column(String, nullable=False)  # day | week | month
    date_info = Column(Text, nullable=False, default="{}")  # JSON
    content = Column(Text, nullable=False, default="")
    proactive_task_id = Column(Integer, nullable=True)
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)


def save_planner_row(
    session,
    *,
    scope: str,
    date_info: dict,
    content: str,
    proactive_task_id: int | None = None,
) -> PlannerOutput:
    """Insert a planner row and commit."""
    row = PlannerOutput(
        scope=scope,
        date_info=json.dumps(date_info, ensure_ascii=False),
        content=content,
        proactive_task_id=proactive_task_id,
    )
    session.add(row)
    session.commit()
    logger.info(
        "save_planner_row: scope=%s proactive_task_id=%s id=%s",
        scope,
        proactive_task_id,
        getattr(row, "id", None),
    )
    return row


def fetch_latest_planner(session, *, scope: str | None = None):
    """Return newest planner row, optionally filtered by ``scope`` (day|week|month)."""
    q = session.query(PlannerOutput).order_by(PlannerOutput.created_at.desc())
    if scope:
        q = q.filter(PlannerOutput.scope == scope)
    return q.first()
