"""Durable planning and evidence artifacts for conversation-first Studio tasks."""

from __future__ import annotations

import json
from typing import Any, Iterable

from distr.core.db import get_session
from distr.core.db.workflow import StudioArtifact


def _serialize(row: StudioArtifact) -> dict[str, Any]:
    try:
        metadata = json.loads(row.metadata_json or "{}")
    except (TypeError, json.JSONDecodeError):
        metadata = {}
    return {
        "id": int(row.id),
        "chat_id": int(row.chat_id),
        "workflow_id": int(row.workflow_id) if row.workflow_id is not None else None,
        "run_id": int(row.run_id) if row.run_id is not None else None,
        "artifact_type": row.artifact_type,
        "title": row.title,
        "summary": row.summary or "",
        "content": row.content or "",
        "content_format": row.content_format or "markdown",
        "uri": row.uri or "",
        "status": row.status or "planned",
        "sort_order": int(row.sort_order or 0),
        "metadata": metadata if isinstance(metadata, dict) else {},
        "created_at": row.created_at.isoformat() if row.created_at else None,
        "modified_at": row.modified_at.isoformat() if row.modified_at else None,
    }


def list_studio_artifacts(chat_id: int) -> list[dict[str, Any]]:
    with get_session() as db:
        rows = (
            db.query(StudioArtifact)
            .filter(StudioArtifact.chat_id == int(chat_id))
            .order_by(StudioArtifact.sort_order.asc(), StudioArtifact.id.asc())
            .all()
        )
        return [_serialize(row) for row in rows]


def create_studio_artifact(
    *,
    chat_id: int,
    artifact_type: str,
    title: str,
    workflow_id: int | None = None,
    run_id: int | None = None,
    summary: str = "",
    content: str = "",
    content_format: str = "markdown",
    uri: str = "",
    status: str = "planned",
    sort_order: int = 0,
    metadata: dict[str, Any] | None = None,
) -> dict[str, Any]:
    with get_session() as db:
        row = StudioArtifact(
            chat_id=int(chat_id),
            workflow_id=int(workflow_id) if workflow_id is not None else None,
            run_id=int(run_id) if run_id is not None else None,
            artifact_type=str(artifact_type or "document").strip().lower(),
            title=str(title or "Artifact").strip(),
            summary=str(summary or "").strip(),
            content=str(content or ""),
            content_format=str(content_format or "markdown").strip().lower(),
            uri=str(uri or "").strip(),
            status=str(status or "planned").strip().lower(),
            sort_order=int(sort_order or 0),
            metadata_json=json.dumps(metadata or {}, ensure_ascii=False, default=str),
        )
        db.add(row)
        db.commit()
        db.refresh(row)
        return _serialize(row)


def seed_studio_artifacts(
    *,
    chat_id: int,
    workflow_id: int,
    execution_profile: str,
    prompt: str,
    steps: Iterable[dict[str, Any]],
) -> list[dict[str, Any]]:
    existing = list_studio_artifacts(chat_id)
    if existing:
        return existing
    step_rows = [
        {
            "id": step.get("id"),
            "name": step.get("name") or f"Step {index + 1}",
            "action_type": step.get("action_type") or "agent_instruction",
            "status": step.get("status") or "pending",
        }
        for index, step in enumerate(steps)
    ]
    profile = str(execution_profile or "code").strip().lower()
    definitions = [
        ("brief", "Outcome brief", "The requested outcome, scope, constraints, and decisions.", "markdown", "ready", prompt),
        ("interface", "Screens and before/after previews", "Wireframes, responsive states, and visual comparisons.", "html", "planned", ""),
        ("architecture", "Architecture and event model", "Components, boundaries, model routes, tools, and handoffs.", "mermaid", "planned", ""),
        ("data_model", "Entities and relationships", "Project, task, ticket, workflow, run, artifact, and evidence relationships.", "mermaid", "planned", ""),
        ("tasks", "Implementation and dependency map", "The executable plan generated by the workflow planner.", "json", "ready", json.dumps(step_rows, ensure_ascii=False, indent=2)),
        ("verification", "Test and evidence plan", "Checks, browser flows, screenshots, corrections, and acceptance evidence.", "markdown", "planned", ""),
    ]
    if profile == "research":
        definitions[1] = ("sources", "Source and claim map", "Sources, claims, confidence, and unresolved questions.", "json", "planned", "")
    elif profile == "operations":
        definitions[1] = ("process", "Process and integration map", "Systems, boards, actions, approvals, and operational handoffs.", "mermaid", "planned", "")
    return [
        create_studio_artifact(
            chat_id=chat_id,
            workflow_id=workflow_id,
            artifact_type=artifact_type,
            title=title,
            summary=summary,
            content_format=content_format,
            status=status,
            content=content,
            sort_order=index,
            metadata={"execution_profile": profile},
        )
        for index, (artifact_type, title, summary, content_format, status, content) in enumerate(definitions)
    ]


def update_studio_artifact(artifact_id: int, **updates: Any) -> dict[str, Any] | None:
    allowed = {"title", "summary", "content", "content_format", "uri", "status", "sort_order", "run_id", "metadata"}
    with get_session() as db:
        row = db.get(StudioArtifact, int(artifact_id))
        if row is None:
            return None
        for key, value in updates.items():
            if key not in allowed or value is None:
                continue
            if key == "metadata":
                row.metadata_json = json.dumps(value or {}, ensure_ascii=False, default=str)
            else:
                setattr(row, key, value)
        db.commit()
        db.refresh(row)
        return _serialize(row)
