"""IDE plugin and harness pack path helpers."""

from distr.core.plugins.paths import (
    CODEX_IDE_DIR,
    CODEX_PLUGIN_NAME,
    COMPETITION_PACK_DIR,
    AGENT_REACH_PACK_DIR,
    COMMUNITY_SKILLS_PACK_DIR,
    CURSOR_IDE_DIR,
    CURSOR_PLUGIN_NAME,
    ECC_VENDOR_DIR,
    PLUGINS_ROOT,
    codex_ide_source,
    competition_fallow_skills_dir,
    competition_ponytail_skills_dir,
    competition_vendor_dir,
    cursor_ide_source,
    ecc_vendor_dir,
    project_root,
    agent_reach_vendor_dir,
    agent_reach_skill_dir,
    agent_reach_skills_root,
    agent_reach_reference_dir,
    yt_dlp_reference_dir,
    community_skills_dir,
)

__all__ = [
    "PLUGINS_ROOT",
    "CODEX_IDE_DIR",
    "CURSOR_IDE_DIR",
    "ECC_VENDOR_DIR",
    "COMPETITION_PACK_DIR",
    "AGENT_REACH_PACK_DIR",
    "COMMUNITY_SKILLS_PACK_DIR",
    "CODEX_PLUGIN_NAME",
    "CURSOR_PLUGIN_NAME",
    "project_root",
    "codex_ide_source",
    "cursor_ide_source",
    "ecc_vendor_dir",
    "competition_vendor_dir",
    "competition_ponytail_skills_dir",
    "competition_fallow_skills_dir",
    "agent_reach_vendor_dir",
    "agent_reach_skill_dir",
    "agent_reach_skills_root",
    "agent_reach_reference_dir",
    "yt_dlp_reference_dir",
    "community_skills_dir",
]
